name: Skill Request
description: Suggest a new skill for the SEO & GEO Skills Library
title: "[Skill Request] "
labels: ["skill-request"]
body:
  - type: input
    id: skill-name
    attributes:
      label: Skill Name
      description: Proposed name (lowercase, hyphens only, 1-64 chars)
      placeholder: e.g., local-seo-optimizer
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this skill belong to?
      options:
        - Research (market analysis — keywords, competitors, SERP, content gaps)
        - Build (content creation — SEO writing, GEO optimization, meta tags, schema)
        - Optimize (improvement — on-page audit, technical SEO, linking, content refresh)
        - Monitor (tracking — rankings, backlinks, performance, alerts)
        - Cross-cutting (spans all phases — quality, authority, entity, memory)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What should this skill do?
      description: Describe the skill's purpose, when users would invoke it, and what output it should produce.
      placeholder: "This skill should... Users would invoke it when they want to... It should output..."
    validations:
      required: true

  - type: textarea
    id: existing-gaps
    attributes:
      label: Why can't existing skills cover this?
      description: Explain why the 20 existing skills don't address this need.
      placeholder: "The closest existing skill is X, but it doesn't handle..."
    validations:
      required: true

  - type: textarea
    id: data-sources
    attributes:
      label: Data sources
      description: What data or tools would this skill need? Use ~~placeholder format.
      placeholder: "Would need ~~SEO tool for keyword data and ~~analytics for traffic data"
    validations:
      required: false
